name: Docs

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    branches:
      - "main"

permissions:
    contents: write

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: Install Hatch
        run: |
          pip install --upgrade pip
          pip install hatch
      - name: Build docs
        run: hatch run docs:build-html
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
