name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  tests:
    name: Tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: Install Hatch
        run: |
          pip --upgrade pip
          pip install hatch
      - name: Pytest
        run: hatch run +py=${{ matrix.python-version }} test:cov
